module.exports = {
  serverError: "serverError",
  userExistsError: "userExistsError",
  detailsError: "detailsError",
  emailError: "emailError",
  phoneNumberError: "phoneNumberError",
  passwordError: "passwordError",
  credentialError: "credentialError",
  tokenError: "tokenError",
  tokenExpiredError: "tokenExpiredError",
  invalidTokenError: "invalidTokenError",
  invalidResetCodeError: "invalidResetCodeError",
  resetCodeAlreadySentError: "resetCodeAlreadySentError",
  resetCodeNotInitiatedError: "resetCodeNotInitiatedError",
  samePasswordError: "samePasswordError",
  useCouponError: "useCouponError",
  subTotalError: "subTotalError",
  totalError: "totalError",
  discountError: "discountError",
  stockError: "stockError",
  amountError: "amountError",
  bookError: "bookError",
  forbiddenError: "forbiddenError",
};
